// Copyright 2020, Nathan Blane

#pragma once

#define VK_PLATFORM_SURFACE_EXTENSION VK_KHR_WIN32_SURFACE_EXTENSION_NAME
#define VK_USE_PLATFORM_WIN32_KHR
#include <vulkan/vulkan.h>

// VMA
#include "vma/vk_mem_alloc.h"

#define CHECK_VK(expression) Assert(expression == VK_SUCCESS)

extern PFN_vkCreateDebugUtilsMessengerEXT vkCreateDebugUtilsMessengerEXT_;
#define vkCreateDebugUtilsMessengerEXT vkCreateDebugUtilsMessengerEXT_

extern PFN_vkDestroyDebugUtilsMessengerEXT vkDestroyDebugUtilsMessengerEXT_;
#define vkDestroyDebugUtilsMessengerEXT vkDestroyDebugUtilsMessengerEXT_

extern PFN_vkSetDebugUtilsObjectNameEXT vkSetDebugUtilsObjectNameEXT_;
#define vkSetDebugUtilsObjectNameEXT vkSetDebugUtilsObjectNameEXT_

extern PFN_vkSetDebugUtilsObjectTagEXT vkSetDebugUtilsObjectTagEXT_;
#define vkSetDebugUtilsObjectTagEXT vkSetDebugUtilsObjectTagEXT_

extern PFN_vkQueueBeginDebugUtilsLabelEXT vkQueueBeginDebugUtilsLabelEXT_;
#define vkQueueBeginDebugUtilsLabelEXT vkQueueBeginDebugUtilsLabelEXT_

extern PFN_vkQueueEndDebugUtilsLabelEXT vkQueueEndDebugUtilsLabelEXT_;
#define vkQueueEndDebugUtilsLabelEXT vkQueueEndDebugUtilsLabelEXT_

extern PFN_vkQueueInsertDebugUtilsLabelEXT vkQueueInsertDebugUtilsLabelEXT_;
#define vkQueueInsertDebugUtilsLabelEXT vkQueueEndDebugUtilsLabelEXT_

extern PFN_vkCmdBeginDebugUtilsLabelEXT vkCmdBeginDebugUtilsLabelEXT_;
#define vkCmdBeginDebugUtilsLabelEXT vkCmdBeginDebugUtilsLabelEXT_

extern PFN_vkCmdEndDebugUtilsLabelEXT vkCmdEndDebugUtilsLabelEXT_;
#define vkCmdEndDebugUtilsLabelEXT vkCmdEndDebugUtilsLabelEXT_

extern PFN_vkCmdInsertDebugUtilsLabelEXT vkCmdInsertDebugUtilsLabelEXT_;
#define vkCmdInsertDebugUtilsLabelEXT vkCmdInsertDebugUtilsLabelEXT_

// Required for VK_EXT_descriptor_heap
extern PFN_vkWriteResourceDescriptorsEXT vkWriteResourceDescriptorsEXT_;
#define vkWriteResourceDescriptorsEXT vkWriteResourceDescriptorsEXT_

extern PFN_vkCmdBindResourceHeapEXT vkCmdBindResourceHeapEXT_;
#define vkCmdBindResourceHeapEXT vkCmdBindResourceHeapEXT_

extern PFN_vkCmdBindSamplerHeapEXT vkCmdBindSamplerHeapEXT_;
#define vkCmdBindSamplerHeapEXT vkCmdBindSamplerHeapEXT_

extern PFN_vkWriteSamplerDescriptorsEXT vkWriteSamplerDescriptorsEXT_;
#define vkWriteSamplerDescriptorsEXT vkWriteSamplerDescriptorsEXT_

extern PFN_vkCmdPushDataEXT vkCmdPushDataEXT_;
#define vkCmdPushDataEXT vkCmdPushDataEXT_